Import("env")

env.Append(
    LINT_SOURCES=[
        Dir("."),
    ],
    CPPPATH=[
        "#/furi",
    ],
)

libenv = env.Clone(FW_LIB_NAME="furi")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)

subdirs = [
    "core",
    "flipper",
]

# Add containerization if this is the base firmware
if env["IS_BASE_FIRMWARE"]:
    subdirs.append("containerization")

libs = []
for subdir in subdirs:
    libs += SConscript(f"{subdir}/SConscript")

Return("libs")
