Import("env")

env.Append(
    CPPPATH=[
        "#/furi/containerization",
    ],
)

libenv = env.Clone(FW_LIB_NAME="containerization")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)

Return("lib")
