name: QA Report Generation

on:
  pull_request:
    branches: [main, "release*", "dev*"]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  merge_report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set environment variables
        run: |
          echo "FBT_TOOLCHAIN_PATH=/tmp/toolchain" >> $GITHUB_ENV
      
      # Explicitly create toolchain directory first
      - name: Create toolchain directory with proper permissions
        run: |
          sudo mkdir -p /tmp/toolchain
          sudo chmod -R 777 /tmp/toolchain
      
      - name: Install dependencies
        run: |
          python3 -m pip install slack_sdk
          
      - name: Generate merge report
        run: |
          source scripts/toolchain/fbtenv.sh || true
          if [ -n "${{ secrets.SLACK_TOKEN }}" ]; then
            python3 scripts/merge_report_qa.py
          else
            echo "No Slack token available, skipping QA report"
          fi
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
