name: Set Up Test Environment

on:
  workflow_call:

jobs:
  setup_test_env:
    runs-on: ubuntu-latest
    steps:
      - name: Create test directories
        run: |
          # Create targets directory structure for API symbol consistency check
          mkdir -p targets/f7 targets/f18
          echo "API_VERSION=1" > targets/f7/api_symbols.csv
          echo "HEADER=test" >> targets/f7/api_symbols.csv
          cp targets/f7/api_symbols.csv targets/f18/api_symbols.csv
          
          # Create coprocessor firmware directory
          mkdir -p lib/stm32wb_copro/firmware
          echo "# Placeholder for copro firmware" > lib/stm32wb_copro/firmware/README.md
          
          # Create dist directories
          mkdir -p dist/f7-firmware/apps/Debug dist/f7-firmware/debug_elf
          mkdir -p dist/f18-firmware/apps/Debug dist/f18-firmware/debug_elf
          
          # Create build directories
          mkdir -p build/f7-firmware build/f18-firmware
          
          # Create assets directory
          mkdir -p assets/resources

          # List created directory structure
          find . -type d | sort
